# Generated by Django 3.1.7 on 2021-05-15 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=10)),
                ('certificate', models.FileField(upload_to='certificate/')),
                ('certificate_status', models.CharField(default='In Process', max_length=10)),
                ('student_id', models.ForeignKey(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='extra_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_performance_row', models.IntegerField(null=True)),
                ('student_profile_row', models.IntegerField(null=True)),
                ('otp', models.CharField(max_length=6)),
                ('photo', models.FileField(upload_to='profile_photo/')),
                ('certificate', models.ForeignKey(null=True, on_delete=lms.models.nothing, to='lms.certificate_request')),
                ('user_id', models.OneToOneField(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('generateddate', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='notice/')),
                ('externallink', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Notice', 'Notice'), ('Placement', 'placement')], default='Notice', max_length=12)),
                ('createdby', models.ForeignKey(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
