# Generated by Django 3.1.7 on 2021-06-04 04:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=10)),
                ('certificate', models.FileField(upload_to='certificate/')),
                ('certificate_status', models.CharField(default='In Process', max_length=10)),
                ('student_id', models.ForeignKey(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='extra_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_performance_row', models.IntegerField(blank=True, null=True)),
                ('student_profile_row', models.IntegerField(blank=True, null=True)),
                ('otp', models.CharField(max_length=6)),
                ('photo', models.FileField(upload_to='profile_photo/')),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=lms.models.nothing, to='lms.certificate_request')),
                ('user_id', models.OneToOneField(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generatedtime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('generator', models.ForeignKey(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('generateddate', models.DateTimeField(default=datetime.datetime.now)),
                ('file', models.FileField(upload_to='notice/')),
                ('externallink', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Notice', 'Notice'), ('Placement', 'placement')], default='Notice', max_length=12)),
                ('createdby', models.ForeignKey(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='groupsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(max_length=15)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
