# Generated by Django 3.1.7 on 2021-04-15 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='expirydate',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='expirytime',
        ),
        migrations.AlterField(
            model_name='notice',
            name='generateddate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
