# Generated by Django 3.1.7 on 2021-05-19 09:58

from django.conf import settings
from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generatedtime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('generator', models.ForeignKey(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
