# Generated by Django 3.1.7 on 2021-05-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lms', '0002_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupsinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.TextField(max_length=15)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
    ]
