# Generated by Django 3.1.7 on 2021-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20210423_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='externallink',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
