# Generated by Django 3.1.7 on 2021-04-26 05:05

from django.conf import settings
from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0005_notice_externallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_performance_row', models.IntegerField()),
                ('photo', models.CharField(max_length=50)),
                ('user_id', models.OneToOneField(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
