# Generated by Django 3.1.7 on 2021-04-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='photo',
            field=models.FileField(upload_to='profile_photo/'),
        ),
    ]
