# Generated by Django 3.1.7 on 2021-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20210426_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='otp',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
