# Generated by Django 3.1.7 on 2021-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_user_profile_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='student_performance_row',
            field=models.IntegerField(null=True),
        ),
    ]
