# Generated by Django 3.1.7 on 2021-05-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_extradata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='extradata',
            new_name='extra_data',
        ),
    ]
