# Generated by Django 3.1.7 on 2021-05-03 04:57

from django.conf import settings
from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0011_auto_20210501_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=10)),
                ('certificate', models.FileField(upload_to='certificate/')),
                ('student_id', models.ForeignKey(on_delete=lms.models.nothing, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
