# Generated by Django 3.1.7 on 2021-05-03 05:03

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_certificate_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate_request',
            name='certificate_status',
            field=models.CharField(default='In Process', max_length=10),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=lms.models.nothing, to='lms.certificate_request'),
        ),
    ]
