# Generated by Django 3.1.7 on 2021-05-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_auto_20210503_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='student_profile_row',
            field=models.IntegerField(null=True),
        ),
    ]
