# Generated by Django 3.1.7 on 2021-05-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210506_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
