# Generated by Django 3.1.7 on 2021-06-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_course_attempts_allowd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='attempts_allowd',
            new_name='attempts_allowed',
        ),
    ]
