# Generated by Django 3.1.7 on 2021-05-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210507_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
