# Generated by Django 3.1.7 on 2021-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210507_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='MCQ', max_length=15),
            preserve_default=False,
        ),
    ]
