# Generated by Django 3.1.7 on 2021-05-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_course_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='questions',
        ),
    ]
