# Generated by Django 3.1.7 on 2021-05-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_attempts_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
