# Generated by Django 3.1.7 on 2021-05-11 04:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0009_auto_20210511_0943'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='exam_attempts',
            unique_together={('student', 'course', 'attempt')},
        ),
    ]
