# Generated by Django 3.1.7 on 2021-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20210511_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_attempts',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
