# Generated by Django 3.1.7 on 2021-05-13 06:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0011_auto_20210513_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program_ans',
            unique_together={('student', 'course', 'program', 'attempt')},
        ),
    ]
