# Generated by Django 3.1.7 on 2021-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20210513_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_attempts',
            name='marks',
            field=models.IntegerField(blank=True),
        ),
    ]
