# Generated by Django 3.1.7 on 2021-05-14 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0013_auto_20210513_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='program_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='programs/')),
                ('attempt', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'course', 'program', 'attempt')},
            },
        ),
    ]
