# Generated by Django 3.1.7 on 2021-05-14 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0014_program_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program_file',
            unique_together={('student', 'course', 'attempt')},
        ),
    ]
