# Generated by Django 3.1.7 on 2021-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20210514_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_attempts',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
